[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
mio = { version = "1.0", features = ["os-poll", "net"] }
protocol = { path = "../protocol" }
bytes = { workspace = true }
derivative = "2.2"
futures = { version = "0.3", default-features = false, features = ["std"] }
indexmap = { version = "2", features = ["serde"] }
futures-timer = "3.0"
thiserror = "2"
rand = "0.9"
tracing = "0.1"

[dev-dependencies]
libc = "0.2.186"
test-log = { version = "0.2", features = ["trace"] }
