//! Generic dispatch for decoding Kafka request/response bodies by API key.
//!
//! This replaces proxy-specific match statements with a single function
//! call that uses the protocol crate's generated types internally.

use bytes::Bytes;
use crate::generated::*;
use crate::traits::{ApiRequest, ApiResponse, ApiVersion, SerializationError};

/// Format a debug string, truncating to a reasonable max length for logging.
fn fmt_compact(s: String) -> String {
    const MAX: usize = 450;
    if s.len() > MAX {
        format!("{} ... ({} chars total)", &s[..MAX], s.len())
    } else {
        s
    }
}

macro_rules! dispatch_decode {
    ($buf:expr, $ver:expr, $api_key:expr, [$($key:expr => $type:ty),+ $(,)?] $(,)?) => {
        match $api_key {
            $(
                $key => <$type>::deserialize($ver, $buf).map(|v| format!("{v:?}")),
            )+
            _ => return Err(format!("unknown api key {}", $api_key)),
        }
    }
}

/// Deserialize a request body for the given API key and version.
pub fn decode_request_body(api_key: i16, version: i16, body: &[u8]) -> Result<String, String> {
    let ver = ApiVersion::new(version);
    let mut buf = Bytes::copy_from_slice(body);
    let result = dispatch_decode!(&mut buf, ver, api_key, [
        0 => ProduceRequest,
        1 => FetchRequest,
        2 => ListOffsetsRequest,
        3 => MetadataRequest,
        4 => LeaderAndIsrRequest,
        5 => StopReplicaRequest,
        6 => UpdateMetadataRequest,
        7 => ControlledShutdownRequest,
        8 => OffsetCommitRequest,
        9 => OffsetFetchRequest,
        10 => FindCoordinatorRequest,
        11 => JoinGroupRequest,
        12 => HeartbeatRequest,
        13 => LeaveGroupRequest,
        14 => SyncGroupRequest,
        15 => DescribeGroupsRequest,
        16 => ListGroupsRequest,
        17 => SaslHandshakeRequest,
        18 => ApiVersionsRequest,
        19 => CreateTopicsRequest,
        20 => DeleteTopicsRequest,
        21 => DeleteRecordsRequest,
        22 => InitProducerIdRequest,
        23 => OffsetForLeaderEpochRequest,
        24 => AddPartitionsToTxnRequest,
        25 => AddOffsetsToTxnRequest,
        26 => EndTxnRequest,
        27 => WriteTxnMarkersRequest,
        28 => TxnOffsetCommitRequest,
        29 => DescribeAclsRequest,
        30 => CreateAclsRequest,
        31 => DeleteAclsRequest,
        32 => DescribeConfigsRequest,
        33 => AlterConfigsRequest,
        34 => AlterReplicaLogDirsRequest,
        35 => DescribeLogDirsRequest,
        36 => SaslAuthenticateRequest,
        37 => CreatePartitionsRequest,
        38 => CreateDelegationTokenRequest,
        39 => RenewDelegationTokenRequest,
        40 => ExpireDelegationTokenRequest,
        41 => DescribeDelegationTokenRequest,
        42 => DeleteGroupsRequest,
        43 => ElectLeadersRequest,
        44 => IncrementalAlterConfigsRequest,
        45 => AlterPartitionReassignmentsRequest,
        46 => ListPartitionReassignmentsRequest,
        47 => OffsetDeleteRequest,
        48 => DescribeClientQuotasRequest,
        49 => AlterClientQuotasRequest,
        50 => DescribeUserScramCredentialsRequest,
        51 => AlterUserScramCredentialsRequest,
        52 => VoteRequest,
        53 => BeginQuorumEpochRequest,
        54 => EndQuorumEpochRequest,
        55 => DescribeQuorumRequest,
        56 => AlterPartitionRequest,
        57 => UpdateFeaturesRequest,
        58 => EnvelopeRequest,
        59 => FetchSnapshotRequest,
        60 => DescribeClusterRequest,
        61 => DescribeProducersRequest,
        62 => BrokerRegistrationRequest,
        63 => BrokerHeartbeatRequest,
        64 => UnregisterBrokerRequest,
        65 => DescribeTransactionsRequest,
        66 => ListTransactionsRequest,
        67 => AllocateProducerIdsRequest,
        68 => ConsumerGroupHeartbeatRequest,
        69 => ConsumerGroupDescribeRequest,
        70 => ControllerRegistrationRequest,
        71 => GetTelemetrySubscriptionsRequest,
        72 => PushTelemetryRequest,
        73 => AssignReplicasToDirsRequest,
        74 => ListConfigResourcesRequest,
        75 => DescribeTopicPartitionsRequest,
        76 => ShareGroupHeartbeatRequest,
        77 => ShareGroupDescribeRequest,
        78 => ShareFetchRequest,
        79 => ShareAcknowledgeRequest,
        80 => AddRaftVoterRequest,
        81 => RemoveRaftVoterRequest,
        82 => UpdateRaftVoterRequest,
        83 => InitializeShareGroupStateRequest,
        84 => ReadShareGroupStateRequest,
        85 => WriteShareGroupStateRequest,
        86 => DeleteShareGroupStateRequest,
        87 => ReadShareGroupStateSummaryRequest,
        88 => StreamsGroupHeartbeatRequest,
        89 => StreamsGroupDescribeRequest,
        90 => DescribeShareGroupOffsetsRequest,
        91 => AlterShareGroupOffsetsRequest,
        92 => DeleteShareGroupOffsetsRequest,
    ]);
    Ok(fmt_compact(result.map_err(|e| format!("{e}"))?))
}

/// Deserialize a response body for the given API key and version.
pub fn decode_response_body(api_key: i16, version: i16, body: &[u8]) -> Result<String, String> {
    let ver = ApiVersion::new(version);
    let mut buf = Bytes::copy_from_slice(body);
    let result = dispatch_decode!(&mut buf, ver, api_key, [
        0 => ProduceResponse,
        1 => FetchResponse,
        2 => ListOffsetsResponse,
        3 => MetadataResponse,
        4 => LeaderAndIsrResponse,
        5 => StopReplicaResponse,
        6 => UpdateMetadataResponse,
        7 => ControlledShutdownResponse,
        8 => OffsetCommitResponse,
        9 => OffsetFetchResponse,
        10 => FindCoordinatorResponse,
        11 => JoinGroupResponse,
        12 => HeartbeatResponse,
        13 => LeaveGroupResponse,
        14 => SyncGroupResponse,
        15 => DescribeGroupsResponse,
        16 => ListGroupsResponse,
        17 => SaslHandshakeResponse,
        18 => ApiVersionsResponse,
        19 => CreateTopicsResponse,
        20 => DeleteTopicsResponse,
        21 => DeleteRecordsResponse,
        22 => InitProducerIdResponse,
        23 => OffsetForLeaderEpochResponse,
        24 => AddPartitionsToTxnResponse,
        25 => AddOffsetsToTxnResponse,
        26 => EndTxnResponse,
        27 => WriteTxnMarkersResponse,
        28 => TxnOffsetCommitResponse,
        29 => DescribeAclsResponse,
        30 => CreateAclsResponse,
        31 => DeleteAclsResponse,
        32 => DescribeConfigsResponse,
        33 => AlterConfigsResponse,
        34 => AlterReplicaLogDirsResponse,
        35 => DescribeLogDirsResponse,
        36 => SaslAuthenticateResponse,
        37 => CreatePartitionsResponse,
        38 => CreateDelegationTokenResponse,
        39 => RenewDelegationTokenResponse,
        40 => ExpireDelegationTokenResponse,
        41 => DescribeDelegationTokenResponse,
        42 => DeleteGroupsResponse,
        43 => ElectLeadersResponse,
        44 => IncrementalAlterConfigsResponse,
        45 => AlterPartitionReassignmentsResponse,
        46 => ListPartitionReassignmentsResponse,
        47 => OffsetDeleteResponse,
        48 => DescribeClientQuotasResponse,
        49 => AlterClientQuotasResponse,
        50 => DescribeUserScramCredentialsResponse,
        51 => AlterUserScramCredentialsResponse,
        52 => VoteResponse,
        53 => BeginQuorumEpochResponse,
        54 => EndQuorumEpochResponse,
        55 => DescribeQuorumResponse,
        56 => AlterPartitionResponse,
        57 => UpdateFeaturesResponse,
        58 => EnvelopeResponse,
        59 => FetchSnapshotResponse,
        60 => DescribeClusterResponse,
        61 => DescribeProducersResponse,
        62 => BrokerRegistrationResponse,
        63 => BrokerHeartbeatResponse,
        64 => UnregisterBrokerResponse,
        65 => DescribeTransactionsResponse,
        66 => ListTransactionsResponse,
        67 => AllocateProducerIdsResponse,
        68 => ConsumerGroupHeartbeatResponse,
        69 => ConsumerGroupDescribeResponse,
        70 => ControllerRegistrationResponse,
        71 => GetTelemetrySubscriptionsResponse,
        72 => PushTelemetryResponse,
        73 => AssignReplicasToDirsResponse,
        74 => ListConfigResourcesResponse,
        75 => DescribeTopicPartitionsResponse,
        76 => ShareGroupHeartbeatResponse,
        77 => ShareGroupDescribeResponse,
        78 => ShareFetchResponse,
        79 => ShareAcknowledgeResponse,
        80 => AddRaftVoterResponse,
        81 => RemoveRaftVoterResponse,
        82 => UpdateRaftVoterResponse,
        83 => InitializeShareGroupStateResponse,
        84 => ReadShareGroupStateResponse,
        85 => WriteShareGroupStateResponse,
        86 => DeleteShareGroupStateResponse,
        87 => ReadShareGroupStateSummaryResponse,
        88 => StreamsGroupHeartbeatResponse,
        89 => StreamsGroupDescribeResponse,
        90 => DescribeShareGroupOffsetsResponse,
        91 => AlterShareGroupOffsetsResponse,
        92 => DeleteShareGroupOffsetsResponse,
    ]);
    Ok(fmt_compact(result.map_err(|e| format!("{e}"))?))
}
